# Generated by Django 3.0.4 on 2020-08-20 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('IDEApp', '0003_ide_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='ide',
            name='input',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
