# Generated by Django 3.0.4 on 2020-08-20 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IDEApp', '0004_ide_input'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ide',
            old_name='input',
            new_name='inp',
        ),
    ]
