# Generated by Django 3.0.4 on 2020-08-20 16:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('IDEApp', '0005_auto_20200820_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='ide',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
