# Generated by Django 3.0.4 on 2020-08-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDEApp', '0006_ide_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ide',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
    ]
