# Generated by Django 3.0.4 on 2020-08-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IDEApp', '0007_auto_20200820_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ide',
            name='file',
        ),
        migrations.AlterField(
            model_name='ide',
            name='inp',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ide',
            name='output',
            field=models.TextField(null=True),
        ),
    ]
