# Generated by Django 3.0.4 on 2020-08-29 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IDEApp', '0010_problem_submission_testcases'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('defination', models.TextField()),
                ('submission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IDEApp.Submission')),
                ('tc_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IDEApp.TestCases')),
            ],
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
