# Generated by Django 3.0.4 on 2020-08-29 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IDEApp', '0011_auto_20200830_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inp', models.TextField()),
                ('out', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='problems',
            name='submission_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IDEApp.Submissions'),
        ),
        migrations.AlterField(
            model_name='problems',
            name='tc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IDEApp.TestCase'),
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.DeleteModel(
            name='TestCases',
        ),
    ]
