# Generated by Django 3.0.4 on 2020-08-29 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IDEApp', '0013_auto_20200830_0216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inp', models.TextField()),
                ('out', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='problem',
            name='submission_id',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='tc_id',
        ),
        migrations.DeleteModel(
            name='Submissions',
        ),
        migrations.DeleteModel(
            name='TestCase',
        ),
        migrations.AddField(
            model_name='testcases',
            name='problem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IDEApp.Problem'),
        ),
        migrations.AddField(
            model_name='submission',
            name='problem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='IDEApp.Problem'),
        ),
    ]
